# Chocofi keyboard build configuration
# Board: Nice Nano v2
# Display: Nice View (optional, remove if not using)
#
# Note: Chocofi uses the Corne shield definition because it's
# electrically compatible. The shield name stays as "corne_left"
# and "corne_right" - this is correct and expected.
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
